In [ ]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
print(max(notlar))
print(min(notlar))
print(sorted(notlar))

notlar = [85, 92, 76, 92, 100, 76, 85, 92]

for eleman in notlar[:]: 
    if notlar.count(eleman) > 1:
        notlar.remove(eleman) 

print(notlar)


100
76
[76, 76, 85, 85, 92, 92, 92, 100]
[100, 76, 85, 92]


In [15]:
#Armstrong sayısı
sayi = int(input("Bir sayı girin: "))
basamak_sayisi = len(str(sayi))
toplam = 0
gecici_sayi = sayi
while gecici_sayi > 0:
    basamak = gecici_sayi % 10
    toplam += basamak ** basamak_sayisi
    gecici_sayi //= 10
if sayi == toplam:
    print(f"{sayi} bir Armstrong sayısıdır.")
else:
    print(f"{sayi} bir Armstrong sayısı değildir.")


153 bir Armstrong sayısıdır.


In [18]:
A = {"Python", "R", "SQL", "Java"} 
B = {"C++", "Python", "JavaScript", "SQL"} 
#ortak elemanlar
ortak_elemanlar = A.intersection(B)
print(ortak_elemanlar)

#sadece A kümesinde olan elemanlar
sadece_A = A.difference(B)
print(sadece_A)

#birleşim kümesi
birlesim = A.union(B)
print(sorted(birlesim))

{'SQL', 'Python'}
{'R', 'Java'}
['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [20]:
#random sayilar
import random
import statistics as stats
sayilar=random.sample(range(1,101),10)
print(sayilar)

print("Ortalama:", stats.mean(sayilar))
print("Standart sapma:", stats.stdev(sayilar))

[26, 47, 9, 30, 90, 76, 77, 41, 45, 60]
Ortalama: 50.1
Standart sapma: 25.553647271747508


In [23]:
def kelime_sayaci(metin):
    kelimeler = metin.split()
    kelime_sayisi = len(kelimeler)
    print(f"Metindeki kelime sayısı: {kelime_sayisi}")
    print("En uzun kelime:" ,max(kelimeler, key=len))
    
    kelimeler = metin.lower().split()
    sayac = {}

    for kelime in kelimeler:
        kelime = kelime.strip(".,!?") 
        sayac[kelime] = sayac.get(kelime, 0) + 1

    # en çok tekrar eden kelimeyi bul
    en_cok = max(sayac, key=sayac.get)
    print("En çok tekrar eden kelime:", en_cok)
    print("Tekrar sayısı:", sayac[en_cok])

metin = input("Bir metin girin: ")
kelime_sayaci(metin)

Metindeki kelime sayısı: 5
En uzun kelime: alaksss
En çok tekrar eden kelime: ala
Tekrar sayısı: 3


In [4]:
#map,filter,sorted kulanımı
sayilar = [5, 12, 7, 18, 24, 3, 16] 
cift=list(filter(lambda x: x%2==0,sayilar))
print(cift)
kareler=list(map(lambda x: x**2,sayilar))
print(sorted(kareler))

[12, 18, 24, 16]
[9, 25, 49, 144, 256, 324, 576]


In [5]:
#kelime uzunluğuna göre sıralama
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"] 
sirali=sorted(kelimeler, key=lambda x:len(x))
print(sirali)

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


In [17]:
#girilen kelimedeki sayıların toplamı
girilen=input("Giriniz:")
toplam=0
for i in girilen:
    if i.isdigit():
        toplam +=int(i)  
print(toplam)

6


In [15]:
import random
import numpy as np


liste=random.sample(range(0,50),10)
dizi=np.array(liste)
print(dizi)

print("Ortalama:", np.mean(dizi))
print("Sapma:", np.std(dizi))
print("Max:" , np.max(dizi))

[12 48 31 43  3  8 17 37 19  7]
Ortalama: 22.5
Sapma: 15.285614151874958
Max: 48


In [22]:

matris=np.random.rand(5,5)
print(matris)
sütun_ort=np.mean(matris,axis=0)
print("Ortalama:",sütun_ort)

binary=(matris>0.5).astype(int)
print(binary)

[[0.28244361 0.05249407 0.85099987 0.28675309 0.96706879]
 [0.89199503 0.82299071 0.35198611 0.00233336 0.13321768]
 [0.5557296  0.08407593 0.29844749 0.24131285 0.16176536]
 [0.58778016 0.27116165 0.36873876 0.11445594 0.65429967]
 [0.02859222 0.35187275 0.25636806 0.09580995 0.93160123]]
Ortalama: [0.46930812 0.31651902 0.42530806 0.14813304 0.56959055]
[[0 0 1 0 1]
 [1 1 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [0 0 0 0 1]]
